"""
Django settings for marketapi project.

Generated by 'django-admin startproject' using Django 3.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os, json, datetime, sys, io, base64
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
BASE_DIR = Path(__file__).resolve().parent.parent

CONFIG_NAME = os.path.join(os.path.join(os.path.dirname(BASE_DIR), "marketapi"), 'config.json')
with open(CONFIG_NAME, "r") as f:
    DB_PARAMS = json.load(f)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+@d8drd&+ub0x+qss22o-xba!5)_fxqj-r1yrigv^n625wl*c!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False

ALLOWED_HOSTS = [
    "125.124.128.89",
    "marketapi.iterated.cn",
    'localhost'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',
    'rest_framework',

    'cores',
    'report',
    'order',
    'wxutils',
    'poi'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware', #cors
    
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'marketapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'marketapi.wsgi.application'
# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': ''
# }
JWT_AUTH = {
    'JWT_RESPONSE_PAYLOAD_HANDLER': 'marketapi.views.JwtResponsePayloadHandler',
    'JWT_EXPIRATION_DELTA': datetime.timedelta(days=1),
}
AUTHENTICATION_BACKENDS = [
    'marketapi.views.CustomBackend',
    # 'django.contrib.auth.backends.ModelBackend',
]
# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

CORS_ORIGIN_WHITELIST = [
    'https://market.iterated.cn',
    'http://localhost:3000',
    'http://127.0.0.1:3000'
]

DATABASES = {
    'default': {
        'ENGINE': str(base64.b64decode(DB_PARAMS['MARKETAPI']['ENGINE']),'utf-8'),
        'NAME': str(base64.b64decode(DB_PARAMS['MARKETAPI']['NAME']),'utf-8'),
        'USER': str(base64.b64decode(DB_PARAMS['MARKETAPI']['USER']),'utf-8'),
        'PASSWORD': str(base64.b64decode(DB_PARAMS['MARKETAPI']['PASSWORD']),'utf-8'),
        'HOST': str(base64.b64decode(DB_PARAMS['MARKETAPI']['HOST']),'utf-8'),
        'PORT': str(base64.b64decode(DB_PARAMS['MARKETAPI']['PORT']),'utf-8'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static_files')
MEDIA_ROOT = os.path.join(BASE_DIR, 'upload_files')
STATIC_URL = '/static/'
MEDIA_URL = '/media/'

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True